[profile.default]
src = 'contracts'
out = 'out'
libs = ['../../lib', '../../node_modules']
allow_paths = ['../']


[profile.default.fuzz]
max_test_rejects = 100000000
runs = 1000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config